### PR TITLE
fix: enforce int for member storage sum

### LINKED ISSUE #6: Enforce integer type for member storage sum

### PR DESCRIPTION
**Pull request by pyphilia**
close #6

### CODE REVIEW

File: index.ts [hunk 1]
```diff
@@ -73,7 +73,7 @@ const plugin: FastifyPluginAsync<GraaspFileUploadLimiterOptions> = async (fastif
             WHERE item.type =${itemType} AND item.creator = ${id}`
         )
         // sum up
-        .then(({ rows }) => rows[0].sum)
+        .then(({ rows }) => parseInt(rows[0].sum, 10))
```
Comment (juancarlosfarah) [inline index.ts]: Might as well factor out the 10 as `DECIMAL` or something.

**Review by juancarlosfarah — APPROVED** [review]
Approved with a minor comment. 👍
